version: '3'

services:

  fractal:
    container_name: fractal-starter-kit

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - .:/app

    working_dir: /app

    environment:
      NODE_ENV: development

    ports:
      - '3333:3333'

    command: yarn start
