version: '3'

services:

  fractal:
    container_name: fractal-starter-kit

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - .:/fractal
      - /fractal/node_modules

    working_dir: /fractal

    environment:
      NODE_ENV: development

    ports:
      - '3333:3333'

    command: npm start
