name: Deploy to Github Pages

on:
  release:
    types:
      - published

jobs:
  deploy:

    name: Deploy to GitHub Pages

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.16'

      - name: Install Node packages
        run: yarn install --pure-lockfile --non-interactive

      - name: Build assets for deployment
        run: yarn run build

      - name: Build Fractal static files
        run: yarn run fractal:build


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v2.10.1
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: build
